### ISSUE TITLE
lucee/lucee52-nginx Missing Sample CFML page

### ISSUE THREAD

**Issue by johnyardstick** [lucee/lucee-dockerfiles#48]
Trying this container out and I am having issues. The sample page that is supposed to exist does not seem to. I get a 403 forbidden when trying to load the sample page or admin. I ssh'd in and found /var/www empty. I imagine im doing something wrong here.

My docker file is simply:

`FROM lucee/lucee52-nginx:latest`

And I have a docker-compose file to bring things up:

```
version: '3'
services:
  app:
    build: .
    ports:
     - "3000:80"
     - "3001:443"
```
